os: osx
osx_image: xcode9

language: java

install:
  - brew install node
  - npm install appdmg

before_script:
  - export P12="CodeSigningCert.p12"
  - export KEYCHAIN="build.keychain"
  - echo $CODE_SIGN_CERT | base64 --decode > $P12
  - security create-keychain -p mysecretpassword $KEYCHAIN
  - security default-keychain -s $KEYCHAIN
  - security unlock-keychain -p mysecretpassword $KEYCHAIN
  - security import $P12 -k $KEYCHAIN -P $CODE_SIGN_PWD -T /usr/bin/codesign

script:
  - cd kse
  - ./gradlew dmg

  