os: osx
osx_image: xcode9

language: java

node_js:
  - "8"
  
install:
  - npm install -g appdmg

before_script:
  - export P12="CodeSigningCert.p12"
  - export KEYCHAIN="build.keychain"
  - echo $CODE_SIGN_CERT | base64 --decode > $P12
  - security create-keychain -p mysecretpassword $KEYCHAIN
  - security default-keychain -s $KEYCHAIN
  - security unlock-keychain -p mysecretpassword $KEYCHAIN
  - security set-keychain-settings $KEYCHAIN
  - security import $P12 -k $KEYCHAIN -P $CODE_SIGN_PWD -T /usr/bin/codesign
  - |-
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k mysecretpassword $KEYCHAIN

script:
  - cd kse
  - which appdmg
  - ./gradlew dmg --stacktrace

  