# https://ci.appveyor.com/tools/validate-yaml

branches:
  only:
    - master

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  NSIS: C:\Program Files (x86)\NSIS
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  #my_secure_var1:
  #  secure: FW3tJ3fMncxvs58/ifSP7w==

install:
  - SET PATH=%JAVA_HOME%\bin;%NSIS%;%PATH%

before_build:
  - cd kse

build:
  verbosity: detailed

build_script:
  - gradlew.bat zip nsis

artifacts:
  - path: build\distributions\kse-*.zip
    name: zip
  - path: build\distributions\kse-*-setup.exe
    name: nsis

#deploy:
#  - provider: GitHub
#    artifact: /.*\.nupkg/
#    draft: false
#    prerelease: false
#    on:
#      branch: master                # release from master branch only
#      appveyor_repo_tag: true       # deploy on tag push only
